auto: true

markdown: kramdown
input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

title: ishanshan'blog
url: http://ishanshan.top
feed: /atom.xml
author_info: <a href="http://ishanshan.top/">ishanshan</a>
